---
bibliography: references.bib
---

# Catching Foxes

Pre-engagement counseling - start working on critical issues now, and plan to resolve them prior to engagement

History (of yourself and spouse) provides context:

Gives you perspective

Allows you to understand each others' vulnerabilities

## Chapter 1 - Personal History

Gospel is the power of God for salvation Rom 1:16

Scripture allows us to :

-   Interpret our history truthfully

-   Respond to our history triumphantly

-   Behold the glory of Christ shining through

God uses our experiences for our good

-   Experiences do not control us

-   God controls our life and destiny

> II Cor 5:14 For the love of Christ controls us, because we have concluded this: that one has died for all, therefore all have died;

History does not determine who you are, but has influenced the way you think, feel, and live and have impacted your view of the world.

Now is the time to honestly discuss secrets from your past - now is the time to be honest

## Chapter 2

Framework for seeing marriage within a larger context:

-   Christ-centered

-   God-exalting

-   Spirit-dependent

Creation- Designed to display and share his glory

Ps 19:1-6 The heavens are telling of his glory

> Col 1:16-17 For by^\[[a](https://www.biblegateway.com/passage/?search=Col%201%3A16-17&version=ESV#fen-ESV-29465a "See footnote a")\]^ him all things were created, in heaven and on earth, visible and invisible, whether thrones or dominions or rulers or authorities—all things were created through him and for him.And he is before all things, and in him all things hold together.

Our personal lives are part of God's redemptive plan

> I Cor 10:31 Whether, then, you eat or drink or whateveryou do, do all to the glory of God

> Ephl:4-6 even as he chose us in him before the foundation of the world, that we should be holy and blameless before him. In love ^**5**^ he predestined us for adoption to himself as sons through Jesus Christ, according to the purpose of his will, ^**6**^ to the praise of his glorious grace, with which he has blessed us in the Beloved.

> I Tim 1:15-17 ^**15**^ The saying is trustworthy and deserving of full acceptance, that Christ Jesus came into the world to save sinners, of whom I am the foremost. ^**16**^ But I received mercy for this reason, that in me, as the foremost, Jesus Christ might display his perfect patience as an example to those who were to believe in him for eternal life. ^**17**^ To the King of the ages, immortal, invisible, the only God, be honor and glory forever and ever.^\[[a](https://www.biblegateway.com/passage/?search=I%20Tim%201%3A15-17&version=ESV#fen-ESV-29697a "See footnote a")\]^ Amen.

-\> Paul was saved not only for his sake, but for God's glory and eternal purposes

> Acts 17:24-28: ^**24**^ The God who made the world and everything in it, being Lord of heaven and earth, does not live in temples made by man,^\[[a](https://www.biblegateway.com/passage/?search=Acts%2017%3A24-28&version=ESV#fen-ESV-27534a "See footnote a")\]^ ^**25**^ nor is he served by human hands, as though he needed anything, since he himself gives to all mankind life and breath and everything.^**26**^ And he made from one man every nation of mankind to live on all the face of the earth, having determined allotted periods and the boundaries of their dwelling place, ^**27**^ that they should seek God, and perhaps feel their way toward him and find him. Yet he is actually not far from each one of us, ^**28**^ for
>
> “‘In him we live and move and have our being’;^\[[b](https://www.biblegateway.com/passage/?search=Acts%2017%3A24-28&version=ESV#fen-ESV-27538b "See footnote b")\]^
>
> as even some of your own poets have said,
>
> “‘For we are indeed his offspring.’^\[[c](https://www.biblegateway.com/passage/?search=Acts%2017%3A24-28&version=ESV#fen-ESV-27538c "See footnote c")\]^

We are created to worship and enjoy God

### Questions:

| **Page 47 - Question #4 “What do you think it means to seek Christ and his Kingdom in your marriage?**\

## Chapter 3

> Gen 1:26-27: ^**6**^ Then God said, “Let us make man^\[[a](https://www.biblegateway.com/passage/?search=gen%201%3A26-27&version=ESV#fen-ESV-26a "See footnote a")\]^ in our image, after our likeness. And let them have dominion over the fish of the sea and over the birds of the heavens and over the livestock and over all the earth and over every creeping thing that creeps on the earth.”
>
> ^**27**^ So God created man in his own image,\
>     in the image of God he created him;\
>     male and female he created them.

1\) We are purposed by God to exist

2: He decided in his mind to form the world anc created us in his likeness

3\) God declared the creation of humans as good.

=\> Every person has God-designed beauty - dignity

Learn to seek God above all else

Learn to be satisfied in Jesus

### FALLEN NATURE

Gen 3:6-7

We revolted -\> humanity died

We began running from God rather than to God

Sinful nature is more than a history of sin

We have adopted a way of Life that devalues God and exults self placed as ruler and savior of our life.

> ROm 7:21-25: ^**21**^ So I find it to be a law that when I want to do right, evil lies close at hand. ^**22**^ For I delight in the law of God, in my inner being, ^**23**^ but I see in my members another law waging war against the law of my mind and making me captive to the law of sin that dwells in my members. ^**24**^ Wretched man that I am! Who will deliver me from this body of death?^**25**^ Thanks be to God through Jesus Christ our Lord! So then, I myself serve the law of God with my mind, but with my flesh I serve the law of sin.

Who loves you enough to tell you you're walking against Christ?

### Corrupted Desires

#### Lust (more than just sexual) James 4:1-2

Source of quarrels: Lusts

#### Fear - an expression of worship (The thingswe fear have power over us)

Lust & Fear go

hand in hand longings -\> fear of missing out

#### Futile attempts to reconcile ourselves to God

Inability to reconcile ourselves to God -\>\> Adam and Eve attempted to cover w/ Skins -\> Hiding From God -\> Blaming one another

### REDEMPTION

Old testament provided temporary deliverance through the shedding of blood.

> Rom 3:21-22 ^**21**^ But now the righteousness of God has been manifested apart from the law, although the Law and the Prophets bear witness to it— ^**22**^ the righteousness of God through faith in Jesus Christ for all who believe. For there is no distinction:

Salvation is more than freedom from sin and death -\> New peaceful relation w/ God

> II Cor 5:14-15: ^**14**^ For the love of Christ controls us, because we have concluded this: that one has died for all, therefore all have died; ^**15**^ and he died for all, that those who live might no longer live for themselves but for him who for their sake died and was raised.

### NEW PERSON

| Questions:  #7 What do you tend to run after for comfort, refuge, and deliverance? Do you run to sports, career, isolation, or something else?

The reality of eternal life, when we consider it truthfully and often enough, controls the way that we live in this present life.

### Questions:

| What kind of rhythms do you have set in your lives for regular accountability - encouragement in a life of repentance and obedience? 
| Page 58 - Question #7 “What do you tend to run after for comfort, refuge, or deliverance? Do you run to sports, food, career, isolation, or something else?”

## Chapter 4

Do you carry a zeal for the eternal purposes of God?

Purpose of Marriage

> Gen 2:18-25: ^**18**^ Then the Lord God said, “It is not good that the man should be alone; I will make him a helper fit for^\[[a](https://www.biblegateway.com/passage/?search=Gen%202%3A18-25&version=ESV#fen-ESV-49a "See footnote a")\]^ him.” ^**19**^ Now out of the ground the Lord God had formed^\[[b](https://www.biblegateway.com/passage/?search=Gen%202%3A18-25&version=ESV#fen-ESV-50b "See footnote b")\]^ every beast of the field and every bird of the heavens and brought them to the man to see what he would call them. And whatever the man called every living creature, that was its name. ^**20**^ The man gave names to all livestock and to the birds of the heavens and to every beast of the field. But for Adam^\[[c](https://www.biblegateway.com/passage/?search=Gen%202%3A18-25&version=ESV#fen-ESV-51c "See footnote c")\]^ there was not found a helper fit for him. ^**21**^ So the Lord God caused a deep sleep to fall upon the man, and while he slept took one of his ribs and closed up its place with flesh. ^**22**^ And the rib that the Lord God had taken from the man he made^\[[d](https://www.biblegateway.com/passage/?search=Gen%202%3A18-25&version=ESV#fen-ESV-53d "See footnote d")\]^ into a woman and brought her to the man. ^**23**^ Then the man said,
>
> “This at last is bone of my bones and flesh of my flesh;\
> she shall be called Woman, because she was taken out of Man.”^\[[e](https://www.biblegateway.com/passage/?search=Gen%202%3A18-25&version=ESV#fen-ESV-54e "See footnote e")\]^
>
> ^**24**^ Therefore a man shall leave his father and his mother and hold fast to his wife, and they shall become one flesh. ^**25**^ And the man and his wife were both naked and were not ashamed.

Marriage doesn't belong to the couple, but belongs to God

No helper suitable for him

For this reason: Leave + cleave

Created to know, enjoy, worship God

Not good to be alone - God was part of a family

Adam had one to love/serve

AND There was no helper suitable for him

Everything created exists to glorfy God

Alone, Adam couldn't display the image of God

Marriage is a gift from God (to be stewarded) for his purposes. =\> God is with us, for us, and committed to our marriages

Marriage is a covenant which pictures, embodies, and points to the eternal covenant between

Christ and the church.

Manage exists as a means of multiplying

Marrage exists to exhort the next generation

But spirtual multiplication is primary -\>

Covenant

Go and make disciples

### Questions: 

| Page 73 - Questions #1-2 Explain what “Let no man separate” means to you 
| What difficulties do you foresee in leaving your original family in order to be joined to your husband or wife? Share ways in which you could be too attached to or dependent upon your father, mother, or siblings - whether this involves their approval, respect, money, or advice
| Page 77 - Questions #5-6 Share your desires for having children or not having children Share your fears about having children

### Chapter 5 Covenant

Noah \~ Rainbow was a sign

Abraham\~ Circumcision

Law as book of the covenant Ex 24:7

New covenant foretold Jer 31:33-34

\
Problem w/ living under the law and judging our

Spouse under the law

Take my yoke, which is easy and my burden light

Col 3:12-13. put on

on a heart of compassion,

Kindness, humility, gentleness and patience

bearing with one another

Forgiving

one another, whoever has a

complaint against anyone - just as

the Lord forgave you,

As we grasp God's compassion for us -\> We have compassion for others

Col 3:14 Let the word dwell within

you richly

→

-\>

teaching and admonishing

one another... Singing with thank-

fullness

Divorce breaks the covenant

I Cor 5:18

God... reconciled himself to

us and gave

reconciliation

us the ministry of

Christian marriage is differents not by

absence of sin but by redeeming and

reconciling Grace

Matt 1929- Whoever durerses a woman.

Mal 2:15 For I hate divorce and him who

covers his

garment

with

wrong

So take heed to

your spirit, that

do not

you

deal treacherously

FREE TO MARRY-

Gen 2:23

Matthew 19:1-10

Mark 10:1

1 Cor 7:10-16\

## Chapter 6 - Becoming a Husband

Epu 5:25 Love your wives,

BECOMING HUSBAND

as Christ also loved the church and gave

himself up

for her

Eph 5:18-21

Filled with the spint

\- New creation

\- Trusting/Honoring Good

-Strengthened in his

power

\- Not ruled by worldly desire

Results of being Filled

-   Speaking is psalms

-   Singing/making melody

-   Giving thanks

-   Being subject to one another

As Christ loved the Church

> John 10:11 I am the Good Shepherd

> Heb 12:2 For the joy set before Him endured the cross, despising the shame

> Col 3:19 Husbands love your wives and do not be embittered against them

As his own body ...nourish and cherish...

With understanding and showing honor

> I Peter 3:7 Live with your wives in an understanding way. Show her honor as a fellow heir of the grace of life

Leaving Parents

## Chapter 7 - Becoming a Wife

Temporal, visible, living picture of the eternal, invisible, living reality of Christ and His church

Wife- display attitudes, affections, activities that Christ should have towards the church

Eph 5- Be filled with the Spirit

We work out our salvation

Phil 2:12-13

It is God who is at work in you

Power for obeying comes from God

John 15:5 I am the vine

Submission + Headship starts in the Godhed

God is the head of Christ I Cor 15:28

...As to the Lord

...In everything - except Sin- Christ would not lead the church into sin...

Submission to Christ overrules submission to husband

.. As is fitting in the Lord = fitting to a Christian Woman

I Pet 3

Precious in the sight of the Lord

Chaste respectful gentle quiet

Ly refuse to use beauty to bring glory

and attention to yourself.

Women's source of hope and protection:

hope in God I Peter 3:5

Leanng Your Parents

Gen 2:24 Men are instructed to leave

their parents, but not women

(culturally) assumed that a woman leaves

her Family because and through marriage

Grooms need to leave and are not

given away'

Is this man someone you can entrust yourself

\

## Chapter 8 - Conflict

Source of all conflict

> James 4:1-4: What causes quarrels and what causes fights among you? Is it not this, that your passions are at war within you? ^**2**^ You desire and do not have, so you murder. You covet and cannot obtain, so you fight and quarrel. You do not have, because you do not ask. ^**3**^ You ask and do not receive, because you ask wrongly, to spend it on your passions.^**4**^ You adulterous people! Do you not know that friendship with the world is enmity with God? Therefore whoever wishes to be a friend of the world makes himself an enemy of God.

→

Idolatry - Desires that lead us to sin to fulfillthem

1.  Corrupt Words.

2.  Rejection of correction

3.  Acting as Two - Acting w/o regard for spouse

4.  Trusting in our own eyes (us God's word)

    -   Cain

    -   Jonah

## Chapter 9

Humble yourself, and he will exalt you

Mariage conflict begins with our war with God

> 2 Peter 1:3-4 His divine power has granted to us all things that pertain to life and godliness, through the knowledge of him who called us to^\[[c](https://www.biblegateway.com/passage/?search=2%20Peter%201&version=ESV#fen-ESV-30466c "See footnote c")\]^ his own glory and excellence,^\[[d](https://www.biblegateway.com/passage/?search=2%20Peter%201&version=ESV#fen-ESV-30466d "See footnote d")\]^ ^**4**^ by which he has granted to us his precious and very great promises, so that through them you may become partakers of the divine nature, having escaped from the corruption that is in the world because of sinful desire. 

cf Unforgiving servant

Need hearts that love God

Ask yourself: What does my heart love so strongly that I am willing to fight for it?

Eager for forgiveness:

-   w/o repentance, we can cover a transgression

-   w/repentance-\> cancel and bring restoration

Trusting the Lord: A trustworthy spouse is a gift, but we are called to trust God

Hands that serve cheerfully

whoever wishes to be great among you shall be your servant

Lips that edify vs Speaks rashly like a sword.

## Chapter 10 Becoming One Flesh

Sexual perversion = false worship

Render the Affection Due

Obstacles-

-   Immorality

    -   Importance of confession/repentance

-   Pornography

    -   Job. I will make a covenant / my eyes.

    -   Mt 5:28 Whoever looks upon a person

    -   Prov 7

-   Past abuse

## Chapter 11 Financial Stewardship

Joseph as arch typical steward

Overseer... Is God's steward

\
