---
bibliography: references.bib
---

# Hebrews

Atonement - 

Ransom Captive - cf Lion/Witch/Wardrobe

  - Puts Satan in the position of power and God as a deceiver
  - Earl
  
Christus Victor - Jesus came to conquer sin and death

  - Crusades 
  - Greg Boyd - Neo Christus Victor
  - Doesn't explain personal atonement
  
Penal Substitutionary Atonement = PSA

  - Sin demands death
  - Jesus dies as a substitute
  - Reformation (Calvin was a lawyer)
  - Set of rules which obligates God's actions
  
Moral Examplar

  - Avalard vs Anselm
  - Resurgence with liberal textual criticism
  - Death required to bring down 
  
Solidarity Theory

  - Solidarity of Christ with humans
  
Scapegoat Theory (Hebraic)

  - Ultimate Sacrifice
  - Sacrifice once for all
  - Michael Hardin
  - Rene Girard's mimetic theory

## Hebrews 8,9,10

Heb 8 - I will make a new covenant, he makes the first one "obsolete" = old

Heb 9 - Sacrifices could not perfect the conscience of the worshiper.

Jesus is temple + priest + sacrifice

How much more will the blood of Jesus cleanse our conscience

Problem with old system - keeps you in bondage to system. Needed to repeat Yom Kippur every year.

Levitical sacrifices did not cleanse the conscience, but reminded worshippers of sin

## Resources:

A Better Atonement - Tony Jones

Did God kill Jesus? - Tony Jones

A Community Called Atonement
