---
bibliography: references.bib
---

# RVL Israel

Mashal - Hebrew Parable (Strong 4911)

Jesus stops funeral procession.- cf Elisha "A prophet has awakened in Israel"

## Gezer

4000BC Glassade

2000BC Cannanite

1300 DC Joshja

City not taken by Joshua. Egyptian king gave Gezer as dowry 950BC

Destroyed

Destroyed again by Babylon

Conquered 15 times in 3500 years

## Cities

- Always found on untillable land 
- Req water source - Place king can store food 
- Defensive position 
- Place of safety 
- Rich lived in cities 
- Surrounded by daughter villages

Don't weep for me, weep for yourselves. The enemies will throw your babies against the wall

You are a city on a hill

4000 extant parables from biblical times:

- Hillel
- A certain man when down to Jericho

### Gezer

### Jaffa = Joppa

- Chief seaport to float cedars of Lebanon to Jersualem for the temple

## Gates

-   Defensive
-   Define relationship to the world
-   Unusual to breach the gates
-   Place of commerce
-   Place of justice Boaz went to city gates
-   Lot - an elder in Sodom and Gomorrah
-   Crucifixion just outside city gates
-   After Babylonian captivity, Jews separated from wider society
-   Nehemiah rebuilt the gates

## Cannanite cosmology

World is conflict between chaos and order (Ma'at)

Yamm is Canaanite God of primordial chaos

Genesis - in the beginning it was chaos, and the spirit of God hovered over the earth

Plagues: 10 gods addressed by 10 plagues

Fall: return to chaos

Jesus: I am the gate

Care for the poor in your gate [@BibleNIV, Deuteronomy 15:7 ]

## Levant Geography

Coastal - Philistines
Foothills

  - Can't farm due to chalk in soil
  - Shephelah

Judean Mountains

  - Farmed in terraces
  
Back Slope

  - 12 miles
  - Wilderness
  
Desert

  - Rift Valley 
  
Valleys - Run East West

- Aijalon - Joshua made sun stand still [@BibleNIV, Joshua 10:12-13]

  - Pass of Beth Horon - Macabees victory
  - Road to Emmaus [@BibleNIV, Luke 24:13-35]
- Sorek
- Elah
- Lachish

## Religious Movements

### Pharisees

- From Hasmodian freedom fighters of Maccabee era
- 6000 middle-class merchants
- Accepted oral interpretation of OT
- Suported synagogue for Torah study and interpretation
- Strict, detailed obedience to Torah and oral law

### Saducees

- Descended from Zadok, Solomon's highest priest
- Formed 200BC
- Priests who were wealthy, aristocratic, and Hellenistic
- Only Torah as God's law
- Temple was the only path to God
- No bodily resurrection
- Dominated Sanhedrin

### Essenes

- Resisted Maccabees claim to high priesthood in 170BC
- Preferred isolation in wilderness
- Ritual cleansing
- Unclear if origin from Pharisees or Saducees

### Zealots

- Formed in opposition to Roman census 6 AD lead by Judas the Galilean
- Extreme Pharisees living in Galilee
- Similar theology to Pharisees, but only God could rule
- Slavery was worst evil
- Taxes due only to God (refused to pay Roman tax)
- Adhered to Torah interpretation
